# Generated by Django 3.2 on 2022-10-14 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20, verbose_name='comment')),
                ('register', models.DateField(default=django.utils.timezone.now, verbose_name='today')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=20, verbose_name='schedule')),
                ('register', models.DateField(default=django.utils.timezone.now, verbose_name='today')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=20, verbose_name='todo')),
                ('complete', models.BooleanField()),
                ('register', models.DateField(default=django.utils.timezone.now, verbose_name='today')),
            ],
        ),
    ]
