# Generated by Django 4.1.2 on 2022-10-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_todo_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateTimeField(verbose_name='today'),
        ),
    ]
