# Generated by Django 4.1.2 on 2022-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_comment_user_id_schedule_user_id_todo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
    ]
