# Generated by Django 4.1.2 on 2022-10-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='temp_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner.comment'),
        ),
        migrations.AddField(
            model_name='todo',
            name='temp_todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner.comment'),
        ),
    ]
