# Generated by Django 4.1.2 on 2022-10-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_schedule_temp_schedule_todo_temp_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='temp_schedule',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='temp_todo',
        ),
    ]
