# Generated by Django 4.1.2 on 2022-10-10 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 5, 41, 15, 929906), verbose_name='today'),
        ),
    ]
