# Generated by Django 4.1.2 on 2022-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateField(blank=True, verbose_name='today'),
        ),
    ]
