# Generated by Django 4.1.2 on 2022-10-10 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 8, 16, 28, 49199), verbose_name='today'),
        ),
    ]
