# Generated by Django 4.1.2 on 2022-10-10 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 8, 17, 7, 762184, tzinfo=datetime.timezone.utc), verbose_name='today'),
        ),
    ]
