# Generated by Django 4.1.2 on 2022-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateField(auto_now_add=True, verbose_name='today'),
        ),
    ]
