# Generated by Django 4.1.2 on 2022-10-10 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 10, 55, 58, 867772, tzinfo=datetime.timezone.utc), verbose_name='today'),
        ),
    ]
