# Generated by Django 4.1.2 on 2022-10-10 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_alter_todo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='register',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='today'),
        ),
    ]
