# Generated by Django 4.1.2 on 2022-10-11 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_alter_todo_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=20, verbose_name='schedule')),
                ('register', models.DateField(default=django.utils.timezone.now, verbose_name='today')),
            ],
        ),
    ]
