# Generated by Django 4.1.2 on 2022-10-11 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20, verbose_name='comment')),
                ('register', models.DateField(default=django.utils.timezone.now, verbose_name='today')),
            ],
        ),
    ]
