# Generated by Django 3.2 on 2022-10-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('subject', models.CharField(max_length=64, verbose_name='과목')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='공부종료한시각')),
                ('time', models.IntegerField(default=0, verbose_name='공부시간')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
    ]
