# Generated by Django 3.2 on 2022-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('image', models.ImageField(default='default.jpeg', upload_to='', verbose_name='이미지')),
                ('info', models.TextField(default='자기소개를 입력해주세요.', verbose_name='자기소개')),
                ('page', models.CharField(default='블로그 주소를 입력해주세요', max_length=50, verbose_name='웹사이트 주소')),
                ('d_day_start', models.DateField(default='2022-10-23', verbose_name='디데이 시작 날짜')),
                ('d_day_end', models.DateField(default='2022-10-23', verbose_name='디데이 끝 날짜')),
                ('d_day', models.CharField(default='0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
            },
        ),
    ]
