# Generated by Django 3.2 on 2022-10-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='d_day_end',
            field=models.DateField(default='2022-10-18', verbose_name='디데이 끝 날짜'),
        ),
        migrations.AddField(
            model_name='user',
            name='d_day_start',
            field=models.DateField(default='2022-10-18', verbose_name='디데이 시작 날짜'),
        ),
        migrations.AlterField(
            model_name='user',
            name='d_day',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(default='자기소개를 입력해주세요.', verbose_name='자기소개'),
        ),
    ]
