# Generated by Django 3.2 on 2022-10-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221018_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page',
            field=models.CharField(default='블로그 주소를 입력해주세요', max_length=50, verbose_name='웹사이트 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='d_day',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='', verbose_name='이미지'),
        ),
    ]
