# Generated by Django 4.1.2 on 2022-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_d_day_end_alter_user_d_day_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='d_day_end',
            field=models.DateField(default='2022-10-21', verbose_name='디데이 끝 날짜'),
        ),
        migrations.AlterField(
            model_name='user',
            name='d_day_start',
            field=models.DateField(default='2022-10-21', verbose_name='디데이 시작 날짜'),
        ),
    ]
