# Generated by Django 3.2 on 2022-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=32)),
                ('startTime', models.CharField(max_length=32)),
                ('endTime', models.CharField(max_length=32)),
                ('totalTime', models.CharField(max_length=32)),
                ('register_dttm', models.DateField()),
            ],
            options={
                'verbose_name': '스탑워치',
                'verbose_name_plural': '스탑워치',
            },
        ),
    ]
