# Generated by Django 3.2 on 2022-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwatch',
            name='register_dttm',
            field=models.CharField(max_length=32),
        ),
    ]
