# Generated by Django 3.2 on 2022-10-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopwatch',
            name='email_id',
        ),
        migrations.AddField(
            model_name='stopwatch',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
